### ISSUE TITLE
Choose color scheme

### ISSUE THREAD

**Issue by nicolemjohnson** [mobileappdevhm20/team-project-team_4#41]
The color scheme needs to be chosen for the app (Primary, Dark, etc...)

**Comment by antonadamsson** [comment]
<img width="304" alt="Skärmavbild 2020-06-01 kl  15 53 28" src="https://user-images.githubusercontent.com/56542651/83423797-c7271e00-a42b-11ea-8291-0ac26014175b.png">

<img width="304" alt="Skärmavbild 2020-06-01 kl  16 00 53" src="https://user-images.githubusercontent.com/56542651/83423815-cdb59580-a42b-11ea-9de5-8e0ba2af7585.png">

<img width="304" alt="Skärmavbild 2020-05-31 kl  16 58 13" src="https://user-images.githubusercontent.com/56542651/83423847-d908c100-a42b-11ea-9b7b-f8eaae317fe0.png">

**Comment by antonadamsson** [comment]
<img width="304" alt="Skärmavbild 2020-06-01 kl  15 53 38" src="https://user-images.githubusercontent.com/56542651/83423919-f2aa0880-a42b-11ea-92e0-e86cee3ab519.png">

<img width="305" alt="Skärmavbild 2020-06-01 kl  16 01 10" src="https://user-images.githubusercontent.com/56542651/83423948-fb9ada00-a42b-11ea-8aa9-fa46ea96d210.png">

<img width="301" alt="Skärmavbild 2020-05-31 kl  16 56 49" src="https://user-images.githubusercontent.com/56542651/83423963-03f31500-a42c-11ea-9026-c2c4a313101d.png">
