### ISSUE TITLE
Reminder should not be manditory

### ISSUE THREAD

**Issue by nicolemjohnson** [mobileappdevhm20/team-project-team_4#89]
When creating a task it is mandatory to have a reminder, but the user should be able to make a task without a reminder

Acceptance Criteria: Make task without reminder

**Comment by nicolemjohnson** [comment]
Not completed in Sprint 2

**Comment by theexiile1305** [comment]
Closed, because it is not really a bug --> The feature _Reminder should not be manditory_ need at least a restructuring of the whole app.
